### ISSUE TITLE
Need Help when launching node.js server

### ISSUE THREAD

**Issue by VadimPlasiciuc** [saturngod/Socket.io-with-iOS#4]
Hi, i have a problem when running server.I am noob so i don't understand how it works .Ii  found this https://github.com/rauchg/chat-example  but when i try to launch ios simulator i get this error 

socketIOexample[5247:245411] [] nw_endpoint_flow_protocol_disconnected [1 192.168.X.X:3000 cancelled socket-flow (null)] Output protocol disconnected

**Comment by saturngod** [comment]
please check correct IP and port number.

**Comment by saturngod** [comment]
This project is already out of date. Please use https://github.com/socketio/socket.io-client-swift
